---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Guest:
    chat: '{prefix}§7{display_name} §f► {msg}'
    nametag: '{prefix}&7{display_name}'
    worlds: []
  Admin:
    chat: '{prefix}{suffix}{display_name} §f► {msg}'
    nametag: '{prefix}{suffix}{display_name}'
    worlds: []
  Owner:
    chat: §aTrum_sv nói là => §c {msg}
    nametag: §l §e Trum_sv §a {display_name}
    worlds: []
  OP:
    chat: '{prefix}{suffix}{display_name} §f► {msg}'
    nametag: '{prefix}{suffix}{display_name}'
    worlds: []
  Vip:
    chat: '{prefix}{suffix}§e{display_name} §f► {msg}'
    nametag: '{prefix}{suffix}§e{display_name}'
    worlds: []
  VipPlus:
    chat: '{prefix}{suffix}§6{display_name} §f► {msg}'
    nametag: '{prefix}{suffix}§6{display_name}'
    worlds: []
  Staff:
    nametag: '{prefix}{suffix}{display_name}'
    chat: '{prefix}{suffix}{display_name} §f► {msg}'
  Youtuber:
    chat: '{prefix}{suffix}§f{display_name} §f► {msg}'
    nametag: '{prefix}{suffix}§f{display_name}'
  Member:
    nametag: '{prefix}{suffix}{display_name}'
    chat: '{prefix}{suffix}{display_name} §f► {msg}'
  VIP1:
    nametag: §l §e VIP§cX §a {display_name}
    chat: §l§eOnii§cChan §a {display_name} §8➩ §e{msg}
...
