# default-currency: Sets default currency
# This configuration could be overridden by external plugin
default-currency: coin
# add-op-at-rank: Set whether to show OPs at top money rank
add-op-at-rank: true
# Whether to allow player to pay when target player is offline
allow-pay-offline: true

# default-lang: Set default language
default-lang: en
# auto-save-interval: Set interval of auto-save
auto-save-interval: 10

# Whether to send command usages of EconomyAPI to client
send-command-usages: true

# List of enabled currencies
currencies:
  coin:
    # Default money given to player who joined the server first time
    default: 0
  gem:
    default: 0

# provider: Set user-provider type of database (Available: yaml, mysql)
provider: yaml

# check-update: Set whether to check update from server
check-update: true
# update-host: Set host where to check update
update-host: onebone.me/plugins/economys/api

# provider-settings: Data which will be given to database provider
provider-settings:
  host: 127.0.0.1
  port: 3306
  user: onebone
  password: hello_world
  db: economyapi
