<?php
declare(strict_types=1);

namespace CustomItems\customies;

use customiesdevs\customies\item\CustomiesItemFactory;

class CustomFishFactory{
	public static function register() : void{
		//Auto generated by NgLamMakeTools
		CustomiesItemFactory::getInstance()->registerItem(Albacore::class, "fi-fish:albacore", "Albacore");
		CustomiesItemFactory::getInstance()->registerItem(Anchovy::class, "fi-fish:anchovy", "Anchovy");
		CustomiesItemFactory::getInstance()->registerItem(Blobfish::class, "fi-fish:blobfish", "Blobfish");
		CustomiesItemFactory::getInstance()->registerItem(BlueDiscus::class, "fi-fish:blue_discus", "Blue Discus");
		CustomiesItemFactory::getInstance()->registerItem(Bream::class, "fi-fish:bream", "Bream");
		CustomiesItemFactory::getInstance()->registerItem(Bullhead::class, "fi-fish:bullhead", "Bullhead");
		CustomiesItemFactory::getInstance()->registerItem(Carp::class, "fi-fish:carp", "Carp");
		CustomiesItemFactory::getInstance()->registerItem(Catfish::class, "fi-fish:catfish", "Catfish");
		CustomiesItemFactory::getInstance()->registerItem(Chub::class, "fi-fish:chub", "Chub");
		CustomiesItemFactory::getInstance()->registerItem(Dorado::class, "fi-fish:dorado", "Dorado");
		CustomiesItemFactory::getInstance()->registerItem(Eel::class, "fi-fish:eel", "Eel");
		CustomiesItemFactory::getInstance()->registerItem(Flounder::class, "fi-fish:flounder", "Flounder");
		CustomiesItemFactory::getInstance()->registerItem(Ghostfish::class, "fi-fish:ghostfish", "Ghostfish");
		CustomiesItemFactory::getInstance()->registerItem(Halibut::class, "fi-fish:halibut", "Halibut");
		CustomiesItemFactory::getInstance()->registerItem(Herring::class, "fi-fish:herring", "Herring");
		CustomiesItemFactory::getInstance()->registerItem(IcePip::class, "fi-fish:ice_pip", "Ice Pip");
		CustomiesItemFactory::getInstance()->registerItem(LargemouthBass::class, "fi-fish:largemouth_bass", "Largemouth Bass");
		CustomiesItemFactory::getInstance()->registerItem(LavaEel::class, "fi-fish:lava_eel", "Lava Eel");
		CustomiesItemFactory::getInstance()->registerItem(Lingcod::class, "fi-fish:lingcod", "Lingcod");
		CustomiesItemFactory::getInstance()->registerItem(Lionfish::class, "fi-fish:lionfish", "Lionfish");
		CustomiesItemFactory::getInstance()->registerItem(MidnightCarp::class, "fi-fish:midnight_carp", "Midnight Carp");
		CustomiesItemFactory::getInstance()->registerItem(MidnightSquid::class, "fi-fish:midnight_squid", "Midnight Squid");
		CustomiesItemFactory::getInstance()->registerItem(MutantCarp::class, "fi-fish:mutant_carp", "Mutant Carp");
		CustomiesItemFactory::getInstance()->registerItem(Octopus::class, "fi-fish:octopus", "Octopus");
		CustomiesItemFactory::getInstance()->registerItem(Perch::class, "fi-fish:perch", "Perch");
		CustomiesItemFactory::getInstance()->registerItem(Pike::class, "fi-fish:pike", "Pike");
		CustomiesItemFactory::getInstance()->registerItem(RadioactiveCarp::class, "fi-fish:radioactive_carp", "Radioactive Carp");
		CustomiesItemFactory::getInstance()->registerItem(RainbowTrout::class, "fi-fish:rainbow_trout", "Rainbow Trout");
		CustomiesItemFactory::getInstance()->registerItem(RedMullet::class, "fi-fish:red_mullet", "Red Mullet");
		CustomiesItemFactory::getInstance()->registerItem(RedSnapper::class, "fi-fish:red_snapper", "Red Snapper");
		CustomiesItemFactory::getInstance()->registerItem(Sandfish::class, "fi-fish:sandfish", "Sandfish");
		CustomiesItemFactory::getInstance()->registerItem(ScorpionCarp::class, "fi-fish:scorpion_carp", "Scorpion Carp");
		CustomiesItemFactory::getInstance()->registerItem(SeaCucumber::class, "fi-fish:sea_cucumber", "Sea Cucumber");
		CustomiesItemFactory::getInstance()->registerItem(Shad::class, "fi-fish:shad", "Shad");
		CustomiesItemFactory::getInstance()->registerItem(Shardine::class, "fi-fish:shardine", "Shardine");
		CustomiesItemFactory::getInstance()->registerItem(Slimejack::class, "fi-fish:slimejack", "Slimejack");
		CustomiesItemFactory::getInstance()->registerItem(SmallmouthBass::class, "fi-fish:smallmouth_bass", "Smallmouth Bass");
		CustomiesItemFactory::getInstance()->registerItem(SpookFish::class, "fi-fish:spook_fish", "Spook Fish");
		CustomiesItemFactory::getInstance()->registerItem(Squid::class, "fi-fish:squid", "Squid");
		CustomiesItemFactory::getInstance()->registerItem(Stingray::class, "fi-fish:stingray", "Stingray");
		CustomiesItemFactory::getInstance()->registerItem(Stonefish::class, "fi-fish:stonefish", "Stonefish");
		CustomiesItemFactory::getInstance()->registerItem(Sturgeon::class, "fi-fish:sturgeon", "Sturgeon");
		CustomiesItemFactory::getInstance()->registerItem(Sunfish::class, "fi-fish:sunfish", "Sunfish");
		CustomiesItemFactory::getInstance()->registerItem(SuperCucumber::class, "fi-fish:super_cucumber", "Super Cucumber");
		CustomiesItemFactory::getInstance()->registerItem(TigerTrout::class, "fi-fish:tiger_trout", "Tiger Trout");
		CustomiesItemFactory::getInstance()->registerItem(Tilapia::class, "fi-fish:tilapia", "Tilapia");
		CustomiesItemFactory::getInstance()->registerItem(Tuna::class, "fi-fish:tuna", "Tuna");
		CustomiesItemFactory::getInstance()->registerItem(VoidSalmon::class, "fi-fish:void_salmon", "Void Salmon");
		CustomiesItemFactory::getInstance()->registerItem(Walleye::class, "fi-fish:walleye", "Walleye");
		CustomiesItemFactory::getInstance()->registerItem(Woodskip::class, "fi-fish:woodskip", "Woodskip");
	}
}