---
# Configuration version, don't edit this.
config-version: 2.1.0

language: en-US

utility:
  # The numbers of accounts to display when using the command.
  top-balance-accounts-limit: 10

currency:
  # The name of the currency.
  name: USD
  # The symbol of the currency.
  symbol: $
  # The string to use for thousands separator.
  number-separator: ","

  balance:
    # The balance for new users.
    default-balance: 100
    # This has no effect if `enable-balance-cap` is false.
    balance-cap: 100000
    # Enabling this will disallow users from exceeding the balance cap.
    enable-balance-cap: false

  payment:
    # The minimum amount of money a user can send.
    minimum-payment: 100
    # The maximum amount of money a user can send.
    maximum-payment: 1000

database:
  # The database provider, mysql or sqlite.
  provider: sqlite
  # Number of threads to use for the database query processing, 2 is recommended.
  threads: 2

  # The database connection information.
  mysql:
    host: 127.0.0.1
    username: your_username
    password: password
    schema: db_name
    port: 3306

  # The database file name.
  sqlite:
    path: players.db
...
