<?php
declare(strict_types=1);

namespace NgLam2911\PlayerProfile;

use pocketmine\event\player\PlayerCreationEvent;
use pocketmine\plugin\PluginBase;

class PlayerProfile extends PluginBase{

	protected function onEnable() : void{
		parent::onEnable(); // TODO: Change the autogenerated stub
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	/**
	 * @param PlayerCreationEvent $event
	 * @priority LOWEST
	 */
	public function onCreation(PlayerCreationEvent $event) : void{
		//nothing
	}
}