<?php
declare(strict_types=1);

namespace Backpack;

use pocketmine\plugin\PluginBase;

class Loader extends PluginBase{

	protected function onEnable() : void{
		parent::onEnable(); // TODO: Change the autogenerated stub
	}

	protected function onDisable() : void{
		parent::onDisable(); // TODO: Change the autogenerated stub
	}
}