<?php
declare(strict_types=1);

namespace CustomItems\custombreaktime;

use NgLamVN\CustomBreakTimeAPI\BaseBreakTime;
use pocketmine\block\Block;
use pocketmine\item\enchantment\EnchantmentInstance;
use pocketmine\item\enchantment\VanillaEnchantments;
use pocketmine\item\Item;
use pocketmine\item\VanillaItems;
use pocketmine\math\Vector3;
use pocketmine\player\Player;

class TitaniumDrillBreakTime extends BaseBreakTime{

	protected function getBreakTime(Block $block, Item $itemuse, Player $player) : int{
		return (int)($block->getBreakInfo()->getBreakTime($this->getBreakItem()) * 20);
	}

	protected function getBreakItem(): Item{
		$item = VanillaItems::DIAMOND_PICKAXE();
		$item->addEnchantment(new EnchantmentInstance(VanillaEnchantments::EFFICIENCY(), 10));
		return $item;
	}

	public function onBreak(Vector3 $pos, Item $item, Player $player, bool $createParticles = true) : void{
		$item = $this->getBreakItem();
		parent::onBreak($pos, $item, $player, $createParticles); // TODO: Change the autogenerated stub
	}
}