<?php
declare(strict_types=1);

namespace CustomItems\custombreaktime;

use NgLamVN\CustomBreakTimeAPI\BaseBreakTime;
use pocketmine\block\Block;
use pocketmine\item\Item;
use pocketmine\item\VanillaItems;
use pocketmine\math\Vector3;
use pocketmine\player\Player;

class TitaniumDrillBreakTime extends BaseBreakTime{

	protected function getBreakTime(Block $block, Item $itemuse, Player $player) : int{
		if ($block->getBreakInfo()->isToolCompatible(VanillaItems::DIAMOND_PICKAXE())){
			return (int)($block->getBreakInfo()->getBreakTime(VanillaItems::DIAMOND_PICKAXE()) * 20 / 3);
		}
		return 999999;
	}

	public function onBreak(Vector3 $pos, Item $item, Player $player, bool $createParticles = true){
		$item = VanillaItems::DIAMOND_PICKAXE();
		parent::onBreak($pos, $item, $player, $createParticles); // TODO: Change the autogenerated stub
	}
}