<?php
declare(strict_types=1);

namespace ItemEditor;

use pocketmine\plugin\PluginBase;

class Loader extends PluginBase{

	public function onEnable() : void{
		parent::onEnable(); // TODO: Change the autogenerated stub
	}

	public function onDisable() : void{
		parent::onDisable(); // TODO: Change the autogenerated stub
	}
}