sell:
  #<item>: price
  cobblestone: 0.1
  iron_ore: 0.5
  gold_ore: 0.5
  diamond: 0.75
  emerald: 0.6
  redstone: 0.1
  lapis_lazuli: 0.1
  coal: 0.2

message:
  # Supported placeholders:
  # {item_name} : Name of item. Ex : "Cobblestone"
  # {count}: Amount of item sold. Ex: 64
  # {total}: Total price. Ex: selling x64 Cobblestone for 6.4 coins (0.1 coins each)
  # {each}: Price of each item. Ex: 0.1
  sell-hand:
    enable: true
    msg: "You sold x{count} {item_name} for {total} coins!"
  sell-all-item-info:
    enable: true
    msg: "Sold x{count} {item_name} for {total} coins!"
  sell-all-total:
    #NOT SUPPORT {item_name} and {each} placeholders
    enable: true
    msg: "Total: {total} coins!"