--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CortexPE/Commando
branches:
- master
- PM4
projects:
  Commando:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.0.1
...
