<?php
declare(strict_types=1);

namespace NgLamVN\FIScore;

use Ifera\ScoreHud\event\PlayerTagUpdateEvent;
use Ifera\ScoreHud\scoreboard\ScoreTag;
use NgLamVN\GameHandle\Season;
use pocketmine\plugin\PluginBase;
use pocketmine\scheduler\ClosureTask;

class Loader extends PluginBase{
	public function onEnable() : void{
		$task = new ClosureTask(function(){
			foreach($this->getServer()->getOnlinePlayers() as $player){
				$ping = $player->getNetworkSession()->getPing();
				if($ping < 80) $color = "§a";
				elseif($ping < 150) $color = "§e";
				elseif($ping < 200) $color = "§6";
				else $color = "§c";

				(new PlayerTagUpdateEvent($player, new ScoreTag("fi-scoreloader.ping", $color . $player->getNetworkSession()->getPing())))->call();
				(new PlayerTagUpdateEvent($player, new ScoreTag("fi-scoreloader.season", Season::getSeason())))->call();
			}
		});
		$this->getScheduler()->scheduleRepeatingTask($task, 5 * 20);

		$this->getServer()->getPluginManager()->registerEvents(new EventListener(), $this);
		$this->getServer()->getPluginManager()->registerEvents(new TagResloveListener(), $this);
	}

	public function onDisable() : void{
		parent::onDisable(); // TODO: Change the autogenerated stub
	}
}
