<?php
declare(strict_types=1);

namespace TestPlugin\entity;

use pocketmine\entity\Zombie;
use pocketmine\player\Player;

class SpinBlockEntity extends Zombie{
	public function onUpdate(int $currentTick) : bool{
		$location = $this->getLocation();
		$location->yaw = mt_rand(0, 359);
		$location->pitch = mt_rand(0, 359);
		$this->location = $location;
		//Move AI
		$target = $this->getPosition()->getWorld()->getNearestEntity($this->getPosition(), 10);
		if ($target == null){
			return parent::onUpdate($currentTick);
		}
		$this->move($target->getPosition()->x, $target->getPosition()->y, $target->getPosition()->z);
		$this->setMovementSpeed(3);
		return parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
	}
}