name: FartBattle
main: NgLamVN\FartBattle\FartBattle
api: 4.0.0
author: NgLamVN
version: 0.1-ngl_alpha
description: JUST FOR FUN :)))

#                 `.`.-.``:s-sysoy/shsyhhyyhyo+..`.````````--.-..-`-..-.`..`-..-.-.-.
#                 `.`.-.``:s-syyyhhhhhhhhhhhhys-.`.````````--.-..-`-..-.`..`-..-.-.-.
#                 `.`.-..:+yyhhhhhhhhhhhhhhhhhhy+-.........--.-..-`-..-.`..`-..-.-.-.
#                 `.-/osyhhhhhhhhhhhhhhhhhhhhhhhhs:------------.--`-..-.`..`-..-.-.-.
#                .-/yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy+-----------------.-.`..`-..-.-.-.`
# `---------------+hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhho:---------------------.-.--.-.-..-----`
# `--------------:shhhhhhhhhhhhhhhhs+///shhhhhhhhhhhho----------------------------.-..-----`
# `---------------ohhhhhhhhhhhhhhh+.````./yhhhhhhhhhhho-----------------------------.------`
# `---------------:ohhhhhhhhhhhhhs.```````-+yhhhhhhhhhy------------------------------------`
# `-----------------/oosyyyhhhhho-`````````.:shhhhhhhh+------------------------------------`
# `-------------------.....-:+/-.````````````-+yhhhhs/-------------------------------------`
# `------------------.`````````````````````````.-:::------------::////++++ssyssss+:--------`
# `------------------````````````````````````````..---:/+++ooyyyyhhhhhhhhhhhhhhhhhho:------`
# `-----------------.``````.``````````````````````.:+yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhho:-----`
# `-----------------.`.-+yhhhs/.``````````````````-shhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs:-----`
# `-----------------.`/ddmmmmmdy-````````````````.+hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy/------`
# `-----------------..ymmmmmmmmm+.```````````````./yhhhhhhhhhhhhhhhhhhhyyyssyhhhyso:-------`
# `------------------.+dmmmmmmmd/```````````````.--/syyyyyyysss+///::--......----.---------`
# `------------------../yhdddhy/.``````````````.----.-----.....``````````````````.---------`
# `-------------------...-:/:-.```````````````.-----.``.-://:-```````````````````.---------`
# `---------------------.```````````````````..------.`-shddddhs-`````````````````.---------`
# `-----------------------..`````````````...--------..hmmmmmmmmy-````````````````.---------.
# `--------------------------...........------------..dmmmmmmmmd/````````````````-----------.`
# `--------------------------------------------------.+ddmmmmmds.```````````````.-------------.
# .---------------------------------------------------.-+shhyo/.``````````````..----------------`
#`-----------------------------------------------------.`````````````````````.-------------------`
#.------------------------------------------------------..`````````````````..---------------------`
#---------------------------:+syyyso+/:--------------------..``````````...-------------------------`
#.-------------------------ohhhhhhhhhhhhyso+/::----------------.......-----------------------------`
#`------------------------+hhhhhhhhhhhhhhhhhhyyso//:-----------------------------------------------.
# `.----------------------+hhhhhhhhhhhhhhhhhhhhhhhhyys+//:------------------------------------------`
#   .----------------------shhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyo+/::------------------------------------.
#    `.---------------------+syyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso+/::------------------------------.
#      .-------------:://///:-:://+osyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysoo/::-------------------------
#       `-----------//////////:-------://+syyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyss+/::-------------------
#        `.--------:///////////:------------://osyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhys+/::--------------
#          .-------:////////////:-----------------:/+osyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso/::--------.
#           `-------////////////:----------------------::/+osyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso/-----.
#             .-----:+///////////-----------------------------:/+osyhhhhhhhhhhhhhhhhhhhhhhhhhhhy/---.
#              `.---:+///////////-------------------:::::::::::::::::/+osyhhhhhhhhhhhhhhhhhhhhhhy:--.
#                `--:+/////////////////////////////////////////////////:--:/+oyhhhhhhhhhhhhhhhhhy:--.
#                  `:+//////////////////////////////////////////////////:------:/+syhhhhhhhhhhhh+---.
#                  .////////////////////////////////////////////////////:-----------:/+osyhhyyo:----.
#                 `/////////////////////////////////////////////////////:----------------:::::------.
#                 .////////////////////////////////////////////////////:----------------------------`
#                  -////////////////////////////////////////////////::----------------------------.`
#                   .:///////////////////////////--------------------------------------------...`
#                     .://///////////////////////------------------------------------..````
#                       .-://////////////////////:------------------------------..``
#                           `.-::::-..://////////:-------------------------..``
#                                      `-///////:--------------------...``
#                                         ``````...---------....```




#yssyyyyssssyyyyyyyyssyo+/:.````                             ```.--::/+/osyyyso:+o+ososyyyyyyyyhyo+yy
#yyyyyyyyyyyyyssssyyysss+:.```                                ```.-/:/+oyssoss/ooosossyyyyyssyyyyysss
#yyyyyyyyyyyhhyyyysoooo+/:.``                                 ```.--:://+osss++++osssssysyssyssssysss
#yyyyyyyyyyyyyyyysssso/:..``                                 ````.-::///ssssoo++++oosysosssssysssooss
#yyyyyyyyyyyysssyysso+:-.``                                  ````.--//:syosooosys/oyyysssyyyyyyssssss
#syyyysyyyhhhhyyyyyys+-.`````                               `````---+/oy+oo+syyyyy+yyyyyyyyyssssyyyyh
#yyyyyhhddddmmmddhhhdho-.````````                      `````````...//oyoosssdhhhhdssdhhdddddhhyyysoss
#yyyhddmmmNNNNNNmmmmddhs/-..``````         ``       ``````````....-:/yosyyhyddddddhodmmmmmmmmmddhyyyy
#hdddmmNNNNNmmddhhdddmddy+:-...```````````````    ````````.......--:++syyyhdddddmmmsdmmmdmmmmmmmmmddh
#dddmmmmNmmdhhhdmmmmmmmmdh+/--.....````````````````````........---:/+oshhyhhdmmmmdhoossssssyyhdmmmmmm
#mmmmmmmdhyyyyhddhymNNNmmdy+/::--....````````````````.......-----::/+syhyhdmmmdhyyhhhmmmmmmdhyssydNmd
#mmmmdmhyyydhyyhyyshdmNmNmds///::--....`````````````.......-------:/oyhhhdmNmyyydNNNdy++hhddmmdyooymm
#mmmddhyyhddmmdhhyyyyymmNmmh+///::--....``````````.......---------:/syhhdmmdyyhNNNdysoossyyyhmmmyoood
#hdhhhyyhmNmmmmdhyyyyyhdmmmds///::--....``````````.......--------::+yhhdmNdyyhmmmdhyysoo++oooydmmy++o
#yhhyyyydNNNmmmmmddmmmmmmmmhy+//::--....``````````......---------:/ohhddmmysymmmmdddhssssyhhhhdmmds+/
#yhhyyyydNNNNNmmmmmmmmmmmmdhh+:::--....````````````......--------:/shyhhmdsoymmmmmmmmmmmmmmmmmmmNms+/
#yyyyysshNNNNNNmmmmmmmmmddhhd+::--..``````````  `````......------:/oyyydmhoosddmmNNmmmmmNmmmmdmmNdo//
#syssyoosmNNNNNmmmmmmmdhhyydd+--..`````          ``````......-----/oyyhmNho+ohddmNNNNNmNNmmmmdddms///
#oos+ssoosdNNmmmmddhhhyyyyhds:..```                  `````......--/oshmdmms++ohdhdmmmmmmmmdhhhmms/:/o
#ooosoyo++oydmmmdhhyyyssshmy+.```                    ````````...-:/osydddNds+/+yhhhddhhhhhhyhhs+::/sd
#oooosydy+//+syhhyssoooymdhs-``                         ```````.-:+ssyhdhhmds+//+ossyhhdhdhhs+:::+hmd
#ooooooyddho/:-::///+ydmhss:``                         ```````..-/osssyyhhdmmho+////++ooo+/:--:+ymmyo
#sooooo+oshddhysosyhdhyo://.`                             `````..-/osooooosyhdddyo+/:------:+yhdhs+//
#sssooo+++++ossssso++/-....`                                 ```..--::::::/++ossyhhhhysosyyhhys+/////
#syysssoooo+++++//:.`` ```                                  `````.``.......-::++++oossssso++/++++o+oo
#ooossooo+/::-..``                                        ````````````````` `.-://+/+++/+///+oooosyys
#ooo++/-.`                   ```                           ```   ` `````      `.-:::/++//+oosyyyyhhhh
#++/:-.`                   ````         ```                 `   `              `.-:////osysyyyhhyhhhy
#+/:..`                  ```````  `````````````  `                             ``.:++///+ossyhhhyhhhh
#/:-.``                 ````````````````````````````````                         `.-:::/++oyyhyhyyhhh
#/-.```                ``.....----.``......````````````                          ``.-:///+ossssshhhhh
#/-.```              ``.---------::----------.....```````                        ``..:/+//+syyhyssyyy
#-.```             ``.-:::::::::::::::::::::::---....````````                   ```.-:::+oo+oosyhyhhh
#..````          ```.-://////////////////////::::--::-..``````                 `````.:/:/+shysssssyyy
#..`````````````````.-:/+osyyo/////////+ydddysssso++/-...``````````  ``           ````.-://+osysssosy
#--...````````````````.:/+ssyhy+/+++//+shmdddhyso+/:-...``````````````````        ````..-:++/+oyyysoo
#:-.........```````````.-/++osss++++//++ossso++/::--.```````````````````````````````````..-/ossooyyhy
#:--------..````````````.-::/++o++++++++++///::----..````````````````````````````````````...-/++oosyy
#::::::-..```````````````.--::/++++oo++++/::----...````````````````````..``````````````....----/+oo+o
#::::--....````````````...----::/+++o+++/:-----....``````````````..``````````.``.............--://oss
#---:-..`` ` ````````.....------://+oo/::------......```````````````````....```..............---:/+oo
#::-.`````````..........---------::/++/:-------.............`````````````````````.................--/
#/-..````..............---------::::///::-------....................``````````````````.............--
#:-....``..`````......--------::::::///:::------............``.........``.``````````````.............
#-.....`````````...----------:::::::////::-------..........```````````............````````...........
#....``````....------:::----:::::::/osso+/::---------.............```````..````....`````````.........
#:-.``.....------------::---:::://+syhhhso+/:::-------.--.............````````````````````````````...
#--....-......---------:--:::://+oyhhdhhyyyso//::-----......................`````````````````````````
#----..........-------:::::://+oyhddddhhhhhyyso+/::-----.........................````````````````````
#::.`..-.....--------::::://+oyyhddddddhyhhdhhhys+/::----............``...````....```````````````````
#-.-::---------------:::://+osyyhyyhhdddhhhdhhddhyyo+/::-----.........```````````````````````````````
#-/:--::----.-------:::::/++osyyyhhhhhddhyhdhhddhdhsoo+/::-----.............`````````````````````````