name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  no_u:
    name: No U checks
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup something
      uses: shivammathur/setup-php@2.21.2
      with:
        php-version: 8.0
    - name: Run
      run: echo "HELLO WORLD"
