name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.2

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff
  no_u:
    name: No U checks
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup something
      uses: shivammathur/setup-php@2.15.0
      with:
        php-version: 8.0
    - name: Run
      run: echo "HELLO WORLD"
